---
- name: 'Beginning Kubernetes Cluster build'
  hosts: localhost
  gather_facts: false
  become: false
  connection: local

  vars_files:
    - common_vars.yml

  tasks:
    - name: 'Getting node information...'
      ansible.builtin.include_tasks: 'include_tasks/get_node_info.yml'
    
    - name: 'Update /etc/hosts'
      ansible.builtin.blockinfile:
        path: /etc/hosts
        block: |
          {{ c1_cp1_public_ip }} c1-cp1.example.com c1-cp1
          {{ c1_node1_public_ip }} c1-node1.example.com c1-node1
      become: true
    
- name: 'Configure c1-cp1'
  hosts: c1-cp1
  become: true
  gather_facts: true
  remote_user: ubuntu

  vars_files:
    - common_vars.yml

  environment:
    ANSIBLE_HOST_KEY_CHECKING: false

  tasks:
    - name: 'Update /etc/hosts'
      ansible.builtin.blockinfile:
        path: /etc/hosts
        block: |
          {{ hostvars['localhost']['c1_cp1_private_ip'] }} c1-cp1.example.com c1-cp1
          {{ hostvars['localhost']['c1_node1_private_ip'] }} c1-node1.example.com c1-node1

    - name: 'Output the join command to use in the following tasks to join nodes to the cluster'
      ansible.builtin.shell:
        cmd: |
          set -o pipefail
          kubeadm token create --print-join-command
        executable: /bin/bash
      changed_when: false

- name: 'Configure c1-cp1'
  hosts: c1-cp1
  become: false
  gather_facts: true
  remote_user: ubuntu

  vars_files:
    - common_vars.yml
  
  environment:
    ANSIBLE_HOST_KEY_CHECKING: false

  tasks:
    - name: 'Copy over kube-flannel.yml'
      ansible.builtin.copy:
        src: kube-flannel.yml
        dest: /home/ubuntu/

    - name: 'Apply kube-flannel.yml'
      ansible.builtin.shell: kubectl apply -f ./kube-flannel.yml

- name: 'Configure c1-node1'
  hosts: c1-node1
  gather_facts: true
  become: true
  remote_user: ubuntu

  vars_files:
    - common_vars.yml

  tasks:
    - name: 'Update /etc/hosts'
      ansible.builtin.blockinfile:
        path: /etc/hosts
        block: |
          {{ hostvars['localhost']['c1_cp1_private_ip'] }} c1-cp1.example.com c1-cp1
          {{ hostvars['localhost']['c1_node1_private_ip'] }} c1-node1.example.com c1-node1

  post_tasks:
    - name: 'Get the join command'
      ansible.builtin.pause:
        prompt: "Please paste in the join command: "
      register: _join_command
      delegate_to: localhost

    - name: 'Run the join-command to join the node to the cluster'
      ansible.builtin.shell:
        cmd: |
          set -o pipefail
          {{ _join_command.user_input }}
        executable: /bin/bash
      changed_when: false

- hosts: c1-cp1
  become: false
  gather_facts: true
  remote_user: ubuntu

  vars_files:
    - common_vars.yml

  environment:
    ANSIBLE_HOST_KEY_CHECKING: false

  roles:
    - install-nginx-gw-fabric

  tasks:
    - name: 'Copy over sample-test1.yaml'
      ansible.builtin.copy:
        src: sample-test1.yaml
        dest: ./sample-test1.yaml

    - name: 'Apply sample-test1.yaml'
      ansible.builtin.shell: kubectl apply -f sample-test1.yaml
...
