---
- name: 'Beginning Kubernetes Cluster build'
  hosts: localhost
  gather_facts: false
  become: false
  connection: local

  vars:
    ansible_python_interpreter: "/home/russest3/repos/aws-vpc-with-client-vpn-endpoint/workspace/.venv/bin/python3"

  vars_files:
    - common_vars.yml

  pre_tasks:
    - name: Check ssh key status
      stat:
        path: ~/.ssh/KubernetesKeyPair.pem
      register: _st

    - name: 'Check that ssh key is setup properly'
      ansible.builtin.assert:
        that:
          - _st.stat.exists
          - _st.stat.mode == '0400'
        fail_msg: 'SSH key is not setup properly.  Please run `make sshkey` and ensure permissions are 0400'

    - ansible.builtin.stat:
        path: "/var/tmp/.baseclusterinstall"
      register: _p

    - ansible.builtin.pause:
        prompt: "It appears the base Kubernetes cluster build has already run.  Do you wish to rerun? (Y/N)"
      when: _p.stat.exists == true
      register: rerun_input

    - ansible.builtin.set_fact:
        _rerun_input: "{{ rerun_input.user_input | lower }}"
      when: _p.stat.exists == true

    - ansible.builtin.set_fact:
        _rerun_input: 'y'
      when: _p.stat.exists == false

  tasks:

    - name: 'Getting node information...'
      ansible.builtin.include_tasks: 'include_tasks/get_node_info.yml'
    
    - name: 'Update /etc/hosts'
      ansible.builtin.blockinfile:
        path: /etc/hosts
        block: |
          {{ c1_cp1_public_ip }} c1-cp1.example.com c1-cp1
          {{ c1_node1_public_ip }} c1-node1.example.com c1-node1
          {{ c1_node2_public_ip }} c1-node2.example.com c1-node2
      become: true
    
- hosts: c1-cp1
  become: true
  gather_facts: true
  remote_user: ubuntu

  vars_files:
    - common_vars.yml

  environment:
    ANSIBLE_HOST_KEY_CHECKING: false

  vars:
    ansible_python_interpreter: '/usr/bin/python3'

  tasks:
    - name: 'Update /etc/hosts'
      ansible.builtin.blockinfile:
        path: /etc/hosts
        block: |
          {{ hostvars['localhost']['c1_cp1_private_ip'] }} c1-cp1.example.com c1-cp1
          {{ hostvars['localhost']['c1_node1_private_ip'] }} c1-node1.example.com c1-node1
          {{ hostvars['localhost']['c1_node2_private_ip'] }} c1-node2.example.com c1-node2

    - name: 'Output the join command to use in the following tasks to join nodes to the cluster'
      ansible.builtin.shell:
        cmd: |
          set -o pipefail
          kubeadm token create --print-join-command
        executable: /bin/bash
      changed_when: false

- name: 'Configure c1-node1'
  hosts: c1-node1
  gather_facts: true
  become: true
  remote_user: ubuntu

  vars_files:
    - common_vars.yml

  vars:
    ansible_python_interpreter: "/usr/bin/python3"

  tasks:
    - name: 'Update /etc/hosts'
      ansible.builtin.blockinfile:
        path: /etc/hosts
        block: |
          {{ hostvars['localhost']['c1_cp1_private_ip'] }} c1-cp1.example.com c1-cp1
          {{ hostvars['localhost']['c1_node1_private_ip'] }} c1-node1.example.com c1-node1
          {{ hostvars['localhost']['c1_node2_private_ip'] }} c1-node2.example.com c1-node2

  post_tasks:
    - name: 'Get the join command'
      ansible.builtin.pause:
        prompt: "Please paste in the join command: "
      register: _join_command
      delegate_to: localhost

    - name: 'Run the join-command to join the node to the cluster'
      ansible.builtin.shell:
        cmd: |
          set -o pipefail
          {{ _join_command.user_input }}
        executable: /bin/bash
      changed_when: false

- name: 'Configure c1-node2'
  hosts: c1-node2
  gather_facts: true
  become: true
  remote_user: ubuntu

  vars_files:
    - common_vars.yml

  vars:
    ansible_python_interpreter: '/usr/bin/python3'

  tasks:
    - name: 'Update /etc/hosts'
      ansible.builtin.blockinfile:
        path: /etc/hosts
        block: |
          {{ hostvars['localhost']['c1_cp1_private_ip'] }} c1-cp1.example.com c1-cp1
          {{ hostvars['localhost']['c1_node1_private_ip'] }} c1-node1.example.com c1-node1
          {{ hostvars['localhost']['c1_node2_private_ip'] }} c1-node2.example.com c1-node2

  post_tasks:
    - name: 'Get the join command'
      ansible.builtin.pause:
        prompt: "Please paste in the join command: "
      register: _join_command
      delegate_to: localhost

    - name: 'Run the join-command to join the node to the cluster'
      ansible.builtin.shell:
        cmd: |
             set -o pipefail
             {{ _join_command.user_input }}
        executable: /bin/bash
      changed_when: false

- hosts: c1-cp1
  become: true
  gather_facts: true
  remote_user: ubuntu

  vars_files:
    - common_vars.yml

  environment:
    ANSIBLE_HOST_KEY_CHECKING: false

  vars:
    ansible_python_interpreter: '/usr/bin/python3'

  tasks:
    - block:
        - name: 'Copy App With LoadBalancer to c1-cp1'
          ansible.builtin.copy:
            src: files/app-load-balancer.yaml
            dest: ./
        - name: 'Executing: App With LoadBalancer'
          ansible.builtin.shell:
            cmd: |
                 set -o pipefail
                 kubectl apply -f app-load-balancer.yaml
...
